import test from 'node:test';
import assert from 'node:assert/strict';
import { chatSheetFixture } from './helpers/chat-sheet-fixture.mjs';

// The sheet tool calls of a dashboard built over a tab and of generated sample data, as a live
// Gemini replay made them: labels beside KPI formulas, edit after edit of one range, a chart over
// a QUERY summary, and a whole table generated by one formula, then frozen to values.

test('set_formulas writes labels, numbers and blanks beside formulas, never text that reads as one', () => {
  const f = chatSheetFixture();
  const result = f.edit(
    'set_formulas',
    {
      formulas: [
        ['Revenue', '=SUM(D2:D20)'],
        ['Orders', '=COUNTA(D2:D20)'],
        ['', 42],
        ['Change', '-5%'],
      ],
    },
    f.inspect('A1:B4')
  );
  assert.equal(result.ok, true);
  assert.deepEqual(
    f.requests()[0].updateCells.rows.map((row) => row.values.map((cell) => cell.userEnteredValue)),
    [
      [{ stringValue: 'Revenue' }, { formulaValue: '=SUM(D2:D20)' }],
      [{ stringValue: 'Orders' }, { formulaValue: '=COUNTA(D2:D20)' }],
      [undefined, { numberValue: 42 }],
      [{ stringValue: 'Change' }, { stringValue: '-5%' }],
    ]
  );
  assert.equal(f.value(f.sheet, 1, 1), 'Revenue');
  assert.equal(f.formula(f.sheet, 1, 1), '');
  assert.equal(f.formula(f.sheet, 2, 2), '=COUNTA(D2:D20)');
  const batches = f.state.batches.length;
  for (const text of ['+B1*2', '-SUM(B1:B2)', ' =B1'])
    assert.throws(
      () => f.edit('set_formulas', { formulas: [['Total', text]] }, f.inspect('A6:B6')),
      /^Error: B6: text starting with [=+-] reads as a formula in Sheets\. Begin a formula with =, or write the label another way\.$/,
      text
    );
  // Formulas beside labels are still checked.
  assert.throws(
    () =>
      f.edit(
        'set_formulas',
        { formulas: [['Feed', '=IMPORTDATA("https://example.com")']] },
        f.inspect('A6:B6')
      ),
    /B6: IMPORTDATA is not allowed/
  );
  assert.equal(f.state.batches.length, batches);
});

test('blank cells written beside an array formula leave room for its result; labels do not', () => {
  const f = chatSheetFixture();
  const header = '={"Transaction ID","Date","Total"}';
  const written = f.edit('set_formulas', { formulas: [[header, '', null]] }, f.inspect('A1:C1'));
  assert.equal(written.ok, true);
  assert.deepEqual(
    written.spills.map((spill) => spill.range),
    ['A1:C1']
  );
  // A cell the edit clears is room too, even when it held data before.
  f.setCell(f.sheet, 5, 2, 'old');
  const cleared = f.edit('set_formulas', { formulas: [[header, '', '']] }, f.inspect('A5:C5'));
  assert.deepEqual(
    cleared.spills.map((spill) => spill.range),
    ['A5:C5']
  );
  assert.throws(
    () => f.edit('set_formulas', { formulas: [[header, '', 'Total']] }, f.inspect('A3:C3')),
    /A3: the result fills A3:C3, which overlaps other cells this edit writes/
  );
  // Two results may not share a blank cell the edit writes: Sheets would show #REF! for one.
  assert.throws(
    () =>
      f.edit(
        'set_formulas',
        { formulas: [['', '=SEQUENCE(3)'], ['={1,2,3}', '']] },
        f.inspect('A7:B8')
      ),
    /A8: the result fills A8:C8, which overlaps other cells this edit writes/
  );
});

test('every edit returns a fresh editToken for its range, single use and bound to the cells as written', () => {
  const f = chatSheetFixture();
  const inspected = f.inspect('A1:B2');
  const values = f.edit(
    'set_values',
    {
      values: [
        ['Revenue', 10],
        ['Orders', 2],
      ],
    },
    inspected
  );
  assert.match(values.editToken, /^e[a-f0-9]{32}$/);
  assert.notEqual(values.editToken, inspected.editToken);
  const formulas = f.edit(
    'set_formulas',
    {
      formulas: [
        ['Revenue', '=SUM(D:D)'],
        ['Orders', '=COUNTA(D2:D)'],
      ],
    },
    values
  );
  const bold = f.edit('format', { format: { bold: true } }, formulas);
  // Analyst actions on the inspected range return one too.
  const noted = f.edit(
    'set_notes',
    {
      notes: [
        ['Sum of column D', ''],
        ['', ''],
      ],
    },
    bold
  );
  assert.match(noted.editToken, /^e[a-f0-9]{32}$/);
  assert.equal(f.state.batches.length, 4);
  // Each token acts once.
  assert.throws(() => f.edit('format', { format: { bold: false } }, bold), /inspection expired/);
  // A token is bound to the cells as the edit left them.
  f.setCell(f.sheet, 2, 1, 'Changed by hand');
  assert.throws(
    () => f.edit('format', { format: { bold: false } }, noted),
    /inspected cells or sheet settings changed/
  );
  assert.equal(f.state.batches.length, 4);
});

test('a token covers edits of any part of its range, and each edit returns one for the whole range again', () => {
  const f = chatSheetFixture();
  const wide = f.inspect('A1:G15');
  const kpis = f.edit(
    'set_formulas',
    {
      range: 'A1:D2',
      formulas: [
        ['Revenue', 'Orders', '', ''],
        ['=SUM(H:H)', '=COUNTA(A:A)', '', ''],
      ],
    },
    wide
  );
  assert.equal(kpis.ok, true);
  assert.equal(kpis.range, 'A1:D2');
  assert.equal(f.formula(f.sheet, 2, 1), '=SUM(H:H)');
  // The fresh token covers the whole inspected range again, as the edit left it.
  const header = f.edit('format', { range: 'A1:D1', format: { bold: true } }, kpis);
  assert.equal(header.ok, true);
  const footer = f.edit('format', { range: 'F15:G15', format: { bold: true } }, header);
  assert.equal(footer.ok, true);
  assert.deepEqual(f.requests()[0].repeatCell.range, {
    sheetId: f.sheet.id,
    startRowIndex: 14,
    endRowIndex: 15,
    startColumnIndex: 5,
    endColumnIndex: 7,
  });
  // Outside the range given, or after a change anywhere in it, the token acts no more.
  const again = f.inspect('A1:G15');
  assert.throws(
    () => f.edit('format', { range: 'G15:H15', format: { bold: true } }, again),
    /inspection expired or belongs to another range/
  );
  f.setCell(f.sheet, 15, 7, 'by hand');
  assert.throws(
    () => f.edit('format', { range: 'A1:B1', format: { bold: true } }, again),
    /inspected cells or sheet settings changed/
  );
  assert.equal(f.state.batches.length, 3);
});

test('create_chart reads header labels as the sheet shows them, over a QUERY result too', () => {
  const summary = [
    ['Department', 'Units Sold', 'Total Revenue'],
    ['Apparel', 12, 640.5],
    ['Grocery', 30, 210],
  ];
  const f = chatSheetFixture({
    setup: (g) => g.book.insertSheet('Data'),
    formulaResult: (formula) => (formula.startsWith('=QUERY') ? summary : undefined),
  });
  f.edit(
    'set_formulas',
    {
      formulas: [
        [
          "=QUERY(Data!A:C,\"select A, sum(B), sum(C) group by A label sum(B) 'Units Sold', sum(C) 'Total Revenue'\",1)",
        ],
      ],
    },
    f.inspect('D1')
  );
  const chart = (input) =>
    f.api.dmvChatCreateChart_(f.session, { sheetName: 'Output', chartType: 'column', ...input });
  assert.equal(
    chart({ range: 'D1:F3', xColumn: 'Department', seriesColumns: ['Total Revenue'] }).ok,
    true
  );
  // A month heading is the date the cell shows, not the date object behind it.
  f.setCell(f.sheet, 10, 1, 'Department');
  f.setCell(f.sheet, 10, 2, new Date('2026-09-01T00:00:00Z'));
  f.setCell(f.sheet, 11, 1, 'Apparel');
  f.setCell(f.sheet, 11, 2, 5);
  assert.equal(
    chart({ range: 'A10:B11', xColumn: 'Department', seriesColumns: ['2026-09-01'] }).ok,
    true
  );
});

test('a generated table is one formula with a guarded spill, frozen by copy_range values onto it', () => {
  const header = [
    'Transaction ID',
    'Date',
    'Store Location',
    'Department',
    'Product Name',
    'Quantity',
    'Unit Price',
    'Total Amount',
    'Payment Method',
  ];
  const formula =
    '={"' +
    header.join('","') +
    '";MAKEARRAY(1000,9,LAMBDA(r,c,CHOOSE(c,"TXN-"&(10000+r),DATE(2026,1,1)+RANDBETWEEN(0,364),' +
    'INDEX({"Downtown","Riverside Mall","Northgate"},RANDBETWEEN(1,3)),' +
    'INDEX({"Electronics","Grocery","Apparel"},RANDBETWEEN(1,3)),' +
    'INDEX({"Wireless Earbuds","Olive Oil 1L","Denim Jacket"},RANDBETWEEN(1,3)),' +
    'RANDBETWEEN(1,5),RANDBETWEEN(500,20000)/100,RANDBETWEEN(500,90000)/100,' +
    'INDEX({"Credit Card","Cash","Mobile Pay"},RANDBETWEEN(1,3)))))}';
  const table = [header].concat(
    Array.from({ length: 1000 }, (_, r) => [
      'TXN-' + (10001 + r),
      46023 + (r % 365),
      'Downtown',
      'Grocery',
      'Olive Oil 1L',
      1 + (r % 5),
      11.99,
      11.99 * (1 + (r % 5)),
      'Cash',
    ])
  );
  // A new tab's 1000 rows.
  const f = chatSheetFixture({
    setup: (g) => (g.sheet.maxRows = 1000),
    formulaResult: (text) =>
      text === formula
        ? table
        : text.startsWith('=QUERY')
          ? [
              ['Department', 'count Transaction ID'],
              ['Grocery', 1000],
              ['', 1],
              ['Apparel', 2],
            ]
          : undefined,
  });
  // The whole result is checked for room before writing, within the tab as it is.
  f.setCell(f.sheet, 500, 2, 'keep');
  assert.throws(
    () => f.edit('set_formulas', { formulas: [[formula]] }, f.inspect('A1')),
    /^Error: A1: the result fills A1:I1001, but 1 cell there holds data \(B500\)\./
  );
  assert.equal(f.state.batches.length, 0);
  f.sheet.cells.delete('500:2');
  // A result past the end of the tab (1000 rows) grows it first, in the same batch: Sheets
  // would show #REF! instead.
  const written = f.edit('set_formulas', { formulas: [[formula]] }, f.inspect('A1'));
  assert.deepEqual(f.requests()[0], {
    appendDimension: { sheetId: f.sheet.id, dimension: 'ROWS', length: 1 },
  });
  assert.equal(f.sheet.maxRows, 1001);
  assert.deepEqual(
    written.spills.map((spill) => spill.range),
    ['A1:I1001']
  );
  assert.equal(f.value(f.sheet, 1001, 9), 'Cash');
  // copy_range values onto the formula's own cell turns its whole result into values, without
  // asking: what the cells show stays the same.
  const frozen = f.edit('copy_range', { destination: 'A1', pasteType: 'values' }, written);
  assert.equal(frozen.ok, true, JSON.stringify(frozen));
  assert.equal(frozen.range, 'A1:I1001');
  assert.deepEqual(f.requests()[0].copyPaste, {
    source: {
      sheetId: f.sheet.id,
      startRowIndex: 0,
      endRowIndex: 1001,
      startColumnIndex: 0,
      endColumnIndex: 9,
    },
    destination: {
      sheetId: f.sheet.id,
      startRowIndex: 0,
      endRowIndex: 1001,
      startColumnIndex: 0,
      endColumnIndex: 9,
    },
    pasteType: 'PASTE_VALUES',
    pasteOrientation: 'NORMAL',
  });
  assert.equal(f.formula(f.sheet, 1, 1), '');
  assert.equal(f.value(f.sheet, 1, 1), 'Transaction ID');
  assert.equal(f.value(f.sheet, 1001, 9), 'Cash');
  assert.equal(f.inspect('H1000:I1001').nonEmptyCells, 4, 'the values are entered now');
  f.undo();
  assert.equal(f.formula(f.sheet, 1, 1), formula);
  // From a range around the formula's cell too: never just part of its result.
  assert.equal(
    f.edit('copy_range', { destination: 'A1', pasteType: 'values' }, f.inspect('A1:C3')).range,
    'A1:I1001'
  );
  assert.equal(f.value(f.sheet, 1001, 9), 'Cash');
  f.undo();
  assert.equal(f.formula(f.sheet, 1, 1), formula);
  // A result whose size only the sheet shows (a QUERY, or MAKEARRAY with a computed size) is
  // frozen as far as it fills the cells right of and below its formula, past an empty value.
  f.edit(
    'set_formulas',
    { formulas: [['=QUERY(A1:I1001,"select D, count(A) group by D",1)']] },
    f.inspect('K1')
  );
  f.setCell(f.sheet, 6, 11, 'below, by hand');
  const summary = f.edit('copy_range', { destination: 'K1', pasteType: 'values' }, f.inspect('K1'));
  assert.equal(summary.range, 'K1:L4');
  assert.deepEqual(
    [1, 2, 3, 4].map((row) => [f.value(f.sheet, row, 11), f.formula(f.sheet, row, 11)]),
    [
      ['Department', ''],
      ['Grocery', ''],
      ['', ''],
      ['Apparel', ''],
    ]
  );
  assert.equal(f.value(f.sheet, 6, 11), 'below, by hand');
  // A formula without an array result freezes just its cell.
  f.edit('set_formulas', { formulas: [['=1+1']] }, f.inspect('N1'));
  assert.equal(
    f.edit('copy_range', { destination: 'N1', pasteType: 'values' }, f.inspect('N1')).range,
    'N1'
  );
  assert.throws(
    () => f.edit('copy_range', { destination: 'A1' }, f.inspect('A1')),
    /The destination is the source itself/
  );
});

test('a freeze never grows over entries of their own or the result of another formula', () => {
  const query = '=QUERY(A1:A9,"select A")';
  const f = chatSheetFixture({
    formulaResult: (text) =>
      text === query
        ? [['Department', 'Orders'], ['Grocery', 1], ['Apparel', 2], ['Home', 3], ['Toys', 4]]
        : text === '=SEQUENCE(1,3)'
          ? [[1, 2, 3]]
          : undefined,
  });
  f.edit('set_formulas', { formulas: [[query]] }, f.inspect('C1'));
  f.setCell(f.sheet, 50, 4, 7, '=SUM(A1:A9)');
  f.edit('set_formulas', { formulas: [['=SEQUENCE(1,3)']] }, f.inspect('B100'));
  assert.equal(f.value(f.sheet, 100, 3), 2);
  const batches = f.state.batches.length;
  assert.throws(
    () => f.edit('copy_range', { destination: 'C1', pasteType: 'values' }, f.inspect('C1')),
    /^Error: C1: the result seems to fill C1:D100, but D50 there holds an entry of its own/
  );
  assert.equal(f.state.batches.length, batches);
  assert.equal(f.formula(f.sheet, 50, 4), '=SUM(A1:A9)');
  assert.equal(f.formula(f.sheet, 100, 2), '=SEQUENCE(1,3)');
});

test('create_sheet takes a row count for a helper tab of formulas and leaves out the tab fields of other actions', () => {
  const f = chatSheetFixture();
  const result = f.tabAction('create_sheet', { newName: 'Monthly', count: 100001 });
  assert.equal(result.ok, true);
  assert.deepEqual(f.requests()[0].addSheet.properties.gridProperties, {
    rowCount: 100001,
    columnCount: 26,
  });
  assert.equal(f.tab('Monthly').maxRows, 100001);
  // The new tab is empty, so its result carries an editToken for its first block: edits there
  // need no inspection.
  assert.equal(result.range, 'A1:Z38');
  const kpis = f.edit(
    'set_formulas',
    { range: 'A1:B1', formulas: [['Revenue', '=SUM(Output!A:A)']] },
    result
  );
  assert.equal(kpis.ok, true);
  assert.equal(f.formula(f.tab('Monthly'), 1, 2), '=SUM(Output!A:A)');
  assert.equal(f.edit('format', { range: 'A1:B1', format: { bold: true } }, kpis).ok, true);
  for (const count of [0, 1.5, '500', 200001])
    assert.throws(
      () => f.tabAction('create_sheet', { newName: 'Other', count }),
      /count|integer|between/i,
      String(count)
    );
  assert.equal(f.state.batches.length, 3);
  // The prompt says tab actions take sheetName, so the tab named beside newName, and an
  // inspection's range and token, are left out rather than refused.
  const named = f.tabAction('create_sheet', {
    newName: 'Dashboard',
    sheetName: 'Output',
    range: 'A1',
    editToken: 'e' + '0'.repeat(32),
  });
  assert.equal(named.ok, true);
  assert.equal(named.sheetName, 'Dashboard');
  assert.equal(f.tab('Dashboard').maxRows, 1000);
});

test('the prompt and tools say each edit returns the next editToken and large data goes through formulas', () => {
  const f = chatSheetFixture();
  const prompt = f.api.dmvChatSystemPrompt_(f.session);
  assert.doesNotMatch(prompt, /reinspect after each edit/i);
  assert.match(
    prompt,
    /editToken \(each edit returns the next one\), sheetName and range or a part of it/
  );
  assert.match(
    prompt,
    /Generate sample data \(about 10 columns unless asked\) as ONE set_formulas formula, header and rows in one array: (=\{.*MAKEARRAY.*RANDBETWEEN.*\}),/
  );
  // The example is a formula the policy accepts, with its whole result guarded.
  const example = /in one array: (=\{.*\}), then freeze/.exec(prompt)[1];
  assert.deepEqual(
    { ...f.api.dmvChatSheetFormulaCheck_(f.session, example, { sheet: f.sheet }).shape },
    { rows: 1001, columns: 3 }
  );
  assert.match(prompt, /then freeze it with copy_range values, range and destination its one cell/);
  assert.match(
    prompt,
    /Never read every row of large data: KPIs are SUMIFS, COUNTIFS, AVERAGEIFS or QUERY over whole columns, charts read a create_pivot summary, not a QUERY/
  );
  assert.match(
    prompt,
    /helper tab of formulas over the source \(create_sheet count: its rows\), never pasted values/
  );
  const tools = Object.fromEntries(f.api.dmvChatTools_(f.session).map((tool) => [tool.name, tool]));
  assert.doesNotMatch(tools.inspect_sheet.description, /after any edit/);
  assert.match(
    tools.edit_sheet.description,
    /its range or a part, and return a fresh editToken for that whole range/
  );
  const edit = tools.edit_sheet.input_schema.properties;
  assert.match(edit.formulas.description, /other cells are values \(labels, numbers\)/);
  assert.match(edit.pasteType.description, /values onto itself freezes formulas/);
  assert.match(edit.count.description, /create_sheet: its rows/);
  assert.match(tools.edit_sheet.description, /tab and row\/column actions \(freeze, filter without a range, insert/);
  assert.match(
    tools.create_chart.input_schema.properties.xColumn.description,
    /as the sheet shows it/
  );
  assert.doesNotMatch(
    tools.create_pivot.description,
    /For money include and group by a currency-code column/
  );
});

test('a matrix of the wrong shape names the shape its range takes', () => {
  const f = chatSheetFixture();
  assert.throws(
    () =>
      f.edit(
        'set_formulas',
        { formulas: [['=SUM(D:D)', '=COUNTA(D:D)', '=AVERAGE(D:D)']] },
        f.inspect('A1:E6')
      ),
    /^Error: The cell matrix must match the inspected range exactly: A1:E6 is 6 rows × 5 columns\.$/
  );
  assert.equal(f.state.batches.length, 0);
});

test('a bracket closed out of order names the call left open', () => {
  const f = chatSheetFixture();
  const check = (formula) =>
    f.api.dmvChatSheetFormulaCheck_(f.session, formula, { sheet: f.sheet, cell: 'A1' });
  // One ")" dropped before the closing brace, as Gemini writes long generators.
  assert.throws(
    () =>
      check(
        '={"ID","Qty";MAKEARRAY(3,2,LAMBDA(r,c,CHOOSE(c,r,RANDBETWEEN(1,9))))}'.replace(
          '))))}',
          ')))}'
        )
      ),
    /^Error: A1: MAKEARRAY\( from character 14 is still open at this "\}": a "\)" is missing \(at character 68, near "\}"\)\.$/
  );
  assert.throws(
    () => check('=SUM({1,2)'),
    /^Error: A1: "\{" from character 6 is still open at this "\)": a "\}" is missing/
  );
  assert.throws(() => check('=(1+2}'), /"\(" from character 2 is still open at this "\}"/);
  assert.deepEqual(
    { ...check('={"ID","Qty";MAKEARRAY(3,2,LAMBDA(r,c,CHOOSE(c,r,RANDBETWEEN(1,9))))}').shape },
    { rows: 4, columns: 2 }
  );
});

test('freeze is a tab action: sheetName alone, and the range and token of an inspection are left out', () => {
  const f = chatSheetFixture();
  const request = (frozenRowCount) => [
    {
      updateSheetProperties: {
        properties: { sheetId: f.sheet.id, gridProperties: { frozenRowCount } },
        fields: 'gridProperties.frozenRowCount',
      },
    },
  ];
  assert.equal(f.tabAction('freeze', { sheetName: f.sheet.name, frozenRows: 1 }).ok, true);
  assert.deepEqual(f.requests(), request(1));
  // As Gemini sends it after other edits: a token without a range, or an inspection.
  const token = f.inspect('A1').editToken;
  assert.equal(
    f.tabAction('freeze', { sheetName: f.sheet.name, editToken: token, frozenRows: 2 }).ok,
    true
  );
  assert.deepEqual(f.requests(), request(2));
  assert.equal(f.edit('freeze', { frozenRows: 0 }, f.inspect('B2')).ok, true);
  assert.deepEqual(f.requests(), request(0));
});

test('a range may name its own tab, as Gemini writes it; another tab is still refused', () => {
  const f = chatSheetFixture({ setup: (g) => g.book.insertSheet('Other') });
  f.column(f.sheet, 1, ['Department', 'Grocery', 'Apparel']);
  f.column(f.sheet, 2, ['Total', 10, 20]);
  assert.equal(f.inspect('Output!A1:B3').range, 'A1:B3');
  assert.equal(f.inspect("'Output'!a1").range, 'A1');
  const format = f.edit(
    'format',
    { range: 'Output!A1:B1', format: { bold: true } },
    f.inspect('A1:B3')
  );
  assert.equal(format.range, 'A1:B1');
  const pivot = f.api.dmvChatCreatePivot_(f.session, {
    sourceSheet: 'Output',
    sourceRange: 'Output!A1:B3',
    targetSheet: 'By department',
    rows: [{ column: 1 }],
    values: [{ column: 2, summarize: 'SUM' }],
  });
  assert.equal(pivot.sourceRange, 'A1:B3');
  const chart = (range) =>
    f.api.dmvChatCreateChart_(f.session, {
      sheetName: 'Output',
      range,
      chartType: 'bar',
      xColumn: 'Department',
      seriesColumns: ['Total'],
    });
  assert.equal(chart('Output!A1:B3').ok, true);
  const batches = f.state.batches.length;
  assert.throws(() => f.inspect('Other!A1'), /^Error: Use an explicit same-tab A1 range/);
  assert.throws(() => chart('Other!A1:B3'), /^Error: Pass the resultId of a table/);
  assert.throws(
    () =>
      f.api.dmvChatCreatePivot_(f.session, {
        sourceSheet: 'Output',
        sourceRange: 'Other!A1:B3',
        targetSheet: 'Elsewhere',
        rows: [{ column: 1 }],
        values: [{ column: 2, summarize: 'SUM' }],
      }),
    /^Error: Use an explicit source range with its header row/
  );
  assert.equal(f.state.batches.length, batches);
});

test('create_pivot returns the range of its summary, so a chart needs no inspection first', () => {
  const f = chatSheetFixture({ setup: (g) => g.book.insertSheet('Dashboard') });
  f.column(f.sheet, 1, ['Department', 'Grocery', 'Apparel', 'Grocery', 'Home']);
  f.column(f.sheet, 2, ['Total', 10, 20, 30, 40]);
  f.column(f.sheet, 3, ['Qty', 1, 2, 3, 4]);
  const pivot = (input) =>
    f.api.dmvChatCreatePivot_(f.session, {
      sourceSheet: 'Output',
      sourceRange: 'A1:C5',
      rows: [{ column: 1 }],
      values: [
        { column: 2, summarize: 'SUM' },
        { column: 3, summarize: 'SUM' },
      ],
      ...input,
    });
  // Its header row and one row per department, on its own tab or at its cell, without the grand
  // total that totals adds below them.
  const tab = pivot({ targetSheet: 'By department' });
  assert.equal(tab.chartRange, 'A1:C4');
  const placed = pivot({ targetSheet: 'Dashboard', targetCell: 'E3', totals: true });
  assert.equal(placed.chartRange, 'E3:G6');
  assert.equal(placed.sheetName, 'Dashboard');
  // Where its rows are not one per group of the rows read, there is none to give.
  for (const input of [
    { columns: [{ column: 3 }], values: [{ column: 2, summarize: 'SUM' }] },
    { rows: [{ column: 1 }, { column: 3 }], values: [{ column: 2, summarize: 'SUM' }] },
    { filters: [{ column: 1, values: ['Grocery'] }] },
  ])
    assert.equal(
      pivot({ targetSheet: 'Other ' + f.state.batches.length, ...input }).chartRange,
      undefined
    );
  // Over a source larger than its checks read, the groups are still counted on every row: Home
  // is only in the last one.
  f.api.DMV_LIMITS.maxRows = 3;
  assert.equal(pivot({ targetSheet: 'Sampled' }).chartRange, 'A1:C4');
});

test('a refused edit says its editToken still holds, so the retry needs no inspection', () => {
  const f = chatSheetFixture();
  const tools = f.api.dmvChatTools_(f.session);
  const call = (input) =>
    JSON.parse(f.api.dmvChatRunTool_(f.session, tools, { name: 'edit_sheet', input }).content);
  const inspected = f.inspect('A1:E6');
  const edit = {
    action: 'set_formulas',
    sheetName: 'Output',
    range: 'A1:E6',
    editToken: inspected.editToken,
  };
  const refused = call({ ...edit, formulas: [['=SUM(D:D)', '=COUNTA(D:D)']] });
  assert.match(refused.error, /^The cell matrix must match the inspected range exactly/);
  assert.equal(
    refused.next,
    'Nothing changed, and the editToken still holds for Output!A1:E6: correct the call and repeat it with that token.'
  );
  const done = call({ ...edit, range: 'A1:B1', formulas: [['=SUM(D:D)', '=COUNTA(D:D)']] });
  assert.equal(done.ok, true);
  // A spent, changed or missing inspection gets no such note.
  const spent = call({ ...edit, range: 'A1', formulas: [['=1']] });
  assert.match(spent.error, /inspection expired/);
  assert.equal(spent.next, undefined);
  const again = f.inspect('A1:B2');
  const retry = { ...edit, range: 'A1:B2', editToken: again.editToken, formulas: [['=1']] };
  assert.ok(call(retry).next);
  f.setCell(f.sheet, 2, 2, 'by hand');
  const changed = call(retry);
  assert.match(changed.error, /inspected cells or sheet settings changed/);
  assert.equal(changed.next, undefined);
  assert.equal(call({ action: 'format', sheetName: 'Output', range: 'A1' }).next, undefined);
});

test('filter without a range is a tab action over the tab data, however large', () => {
  const f = chatSheetFixture({
    setup: (g) => {
      g.book.sheets[0].maxRows = 1001;
      g.book.sheets[0].maxColumns = 10;
    },
  });
  for (let c = 1; c <= 10; c++) f.setCell(f.sheet, 1, c, 'Column ' + c);
  for (let r = 2; r <= 1001; r++) f.setCell(f.sheet, r, 1, r);
  // As Gemini sends it after other edits: sheetName alone, or with a token but no range.
  const result = f.tabAction('filter', {
    sheetName: 'Output',
    editToken: f.inspect('A1').editToken,
    filter: { column: 1, condition: 'NUMBER_GREATER', value: 5 },
  });
  assert.equal(result.ok, true);
  assert.equal(result.range, 'A1:J1001');
  const filter = f.requests()[0].setBasicFilter.filter;
  assert.deepEqual(filter.range, {
    sheetId: f.sheet.id,
    startRowIndex: 0,
    endRowIndex: 1001,
    startColumnIndex: 0,
    endColumnIndex: 10,
  });
  assert.deepEqual(Object.keys(filter.criteria), ['0']);
  // The filter it made is kept; one over another range is refused as before.
  assert.equal(f.tabAction('filter', { sheetName: 'Output', filter: {} }).ok, true);
  assert.deepEqual(Object.keys(f.requests()[0].setBasicFilter.filter.criteria), ['0']);
  const small = chatSheetFixture();
  small.column(small.sheet, 1, ['Name', 'a', 'b']);
  small.edit('filter', { filter: {} }, small.inspect('A1:A3'));
  small.setCell(small.sheet, 1, 2, 'Total');
  assert.throws(
    () => small.tabAction('filter', { sheetName: 'Output' }),
    /An existing filter covers a different range/
  );
  const empty = chatSheetFixture();
  assert.throws(
    () => empty.tabAction('filter', { sheetName: 'Output' }),
    /^Error: The tab has no data to filter\.$/
  );
});

test('the prompt and tools put pivots and charts before formats, and chart a pivot by its chartRange', () => {
  const f = chatSheetFixture();
  const prompt = f.api.dmvChatSystemPrompt_(f.session);
  assert.match(
    prompt,
    /\(for data already in a tab: a new tab in small calls: edit_sheet KPI formulas, create_pivot, create_chart over its chartRange, then at most two format calls over whole blocks; not save_dashboard\)/
  );
  const tools = Object.fromEntries(f.api.dmvChatTools_(f.session).map((tool) => [tool.name, tool]));
  assert.match(tools.create_pivot.description, /chartRange/);
  assert.match(tools.edit_sheet.description, /\(freeze, filter without a range, insert/);
  assert.match(
    tools.edit_sheet.input_schema.properties.filter.description,
    /Without range: the tab's data/
  );
});
